<#
.SYNOPSIS
    Crée un snapshot d'un fichier avant modification

.DESCRIPTION
    Ce script crée une copie de sauvegarde (snapshot) d'un fichier dans le dossier 
    .kiro-backup/snapshots/ avant toute modification, permettant un rollback facile.
    
    Le système de snapshots remplace l'ancienne méthode des commentaires dans les fichiers,
    gardant ainsi les fichiers propres et lisibles (notamment les fichiers JSON).

.VERSION
    1.0.0

.LAST UPDATE
    2026-02-04

.AUTHOR
    Kiro

.CHANGELOG
    v1.0.0 (2026-02-04) : Création initiale

.PARAMETER File
    Chemin du fichier à sauvegarder (relatif ou absolu)

.PARAMETER Description
    Description de la modification prévue (optionnel)

.PARAMETER Palier
    Numéro du palier de migration (optionnel, défaut: 0)

.EXAMPLE
    .\snapshot-file.ps1 -File "pwc-ui/pwc-ui-v4-ia/package.json"

.EXAMPLE
    .\snapshot-file.ps1 -File "pwc-ui/pwc-ui-v4-ia/package.json" -Description "Ajout de json-ignore" -Palier 1
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$File,
    
    [Parameter(Mandatory=$false)]
    [string]$Description = "",
    
    [Parameter(Mandatory=$false)]
    [int]$Palier = 0
)

# Configuration
$backupRoot = ".kiro-backup"
$snapshotsDir = "$backupRoot/snapshots"
$diffsDir = "$backupRoot/diffs"
$indexFile = ".kiro/state/modifications-index.json"

# Vérifier que le fichier existe
if (-not (Test-Path $File)) {
    Write-Error "❌ Fichier non trouvé : $File"
    exit 1
}

# Générer un ID unique
$modId = "mod-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
$date = Get-Date -Format "yyyy-MM-dd"
$timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"

# Créer les dossiers si nécessaire
$snapshotDateDir = "$snapshotsDir/$date"
if (-not (Test-Path $snapshotDateDir)) {
    New-Item -ItemType Directory -Path $snapshotDateDir -Force | Out-Null
    Write-Host "📁 Dossier créé : $snapshotDateDir"
}

if (-not (Test-Path $diffsDir)) {
    New-Item -ItemType Directory -Path $diffsDir -Force | Out-Null
    Write-Host "📁 Dossier créé : $diffsDir"
}

# Extraire le nom du fichier
$fileName = Split-Path $File -Leaf
$snapshotFile = "$snapshotDateDir/$modId-$fileName"

# Créer le snapshot
Copy-Item $File $snapshotFile -Force
Write-Host "✅ Snapshot créé : $snapshotFile"

# Préparer l'entrée pour l'index
$modification = @{
    id = $modId
    date = $timestamp
    author = "Kiro"
    file = $File
    type = "modification"
    description = $Description
    reason = ""
    snapshot = $snapshotFile
    diff = "$diffsDir/$modId.diff"
    palier = $Palier
    relatedJournalEntry = $date
    status = "pending"
    rollbackTested = $false
}

# Lire l'index existant ou créer un nouveau
if (Test-Path $indexFile) {
    $index = Get-Content $indexFile -Raw | ConvertFrom-Json
} else {
    $index = @{
        metadata = @{
            version = "2.0.0"
            lastUpdate = $date
            system = "snapshots"
        }
        config = @{
            snapshotsDir = $snapshotsDir
            diffsDir = $diffsDir
            retentionDays = 30
            autoGenerateDiff = $true
        }
        modifications = @()
    }
}

# Ajouter la modification à l'index
$index.modifications += $modification
$index.metadata.lastUpdate = $date

# Sauvegarder l'index
$index | ConvertTo-Json -Depth 10 | Set-Content $indexFile -Encoding UTF8
Write-Host "✅ Index mis à jour : $indexFile"

# Afficher le résumé
Write-Host ""
Write-Host "📸 SNAPSHOT CRÉÉ"
Write-Host "================"
Write-Host "ID          : $modId"
Write-Host "Fichier     : $File"
Write-Host "Snapshot    : $snapshotFile"
Write-Host "Description : $Description"
Write-Host "Palier      : $Palier"
Write-Host ""
Write-Host "⚠️  N'oubliez pas de générer le diff après modification :"
Write-Host "    .\scripts_outils_ia\generate-diff.ps1 -ModificationId $modId"
Write-Host ""

# Retourner l'ID pour utilisation ultérieure
return $modId
